// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    partial class BookStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Account", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TenTaiKhoan");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TaoLuc")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ten");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("LanguagePreference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NgonNguUaThich");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ho");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoDienThoai");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("MaQuyen");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CapNhatLuc")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Username");

                    b.HasIndex("RoleId");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            Username = "vuongthai",
                            Address = "Hà Nội",
                            Avatar = "https://example.com/avatar1.jpg",
                            CreatedAt = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vuongthai@example.com",
                            FirstName = "Nguyễn",
                            Gender = "Nam",
                            LanguagePreference = "Tiếng Việt",
                            LastName = "Văn A",
                            Password = "$2a$13$6BjHaarncKGYIgYiBmcg8OVbItdMJuyiXjmuCokUpitoUjbBVvCFy",
                            PhoneNumber = "0123456789",
                            RoleId = 1,
                            Status = "1",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Username = "user2",
                            Address = "TP. Hồ Chí Minh",
                            Avatar = "https://example.com/avatar2.jpg",
                            CreatedAt = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2@example.com",
                            FirstName = "Trần",
                            Gender = "Nữ",
                            LanguagePreference = "Tiếng Anh",
                            LastName = "Thị B",
                            Password = "$2a$13$6BjHaarncKGYIgYiBmcg8OVbItdMJuyiXjmuCokUpitoUjbBVvCFy",
                            PhoneNumber = "0987654321",
                            RoleId = 2,
                            Status = "1",
                            UpdatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Username = "user3",
                            Address = "Đà Nẵng",
                            Avatar = "https://example.com/avatar3.jpg",
                            CreatedAt = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1994, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user3@example.com",
                            FirstName = "Phạm",
                            Gender = "Nam",
                            LanguagePreference = "Tiếng Việt",
                            LastName = "Văn C",
                            Password = "$2a$13$6BjHaarncKGYIgYiBmcg8OVbItdMJuyiXjmuCokUpitoUjbBVvCFy",
                            PhoneNumber = "0777666555",
                            RoleId = 2,
                            Status = "1",
                            UpdatedAt = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Username = "staff",
                            Address = "Đà Nẵng",
                            Avatar = "https://example.com/avatar3.jpg",
                            CreatedAt = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1994, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@example.com",
                            FirstName = "Phạm",
                            Gender = "Nam",
                            LanguagePreference = "Tiếng Việt",
                            LastName = "Văn C",
                            Password = "$2a$13$6BjHaarncKGYIgYiBmcg8OVbItdMJuyiXjmuCokUpitoUjbBVvCFy",
                            PhoneNumber = "0777666555",
                            RoleId = 3,
                            Status = "1",
                            UpdatedAt = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("backend.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSach");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TacGia");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TaoLuc")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaTien");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CapNhatLuc")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Sach");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Nguyễn Văn A",
                            CategoryId = 1,
                            CreateAt = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sách hướng dẫn lập trình C# từ cơ bản đến nâng cao.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 29000m,
                            Quantity = 50,
                            Title = "Sách Lập trình C#",
                            UpdateAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Trần Văn B",
                            CategoryId = 2,
                            CreateAt = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sách hướng dẫn lập trình Java cho người mới bắt đầu.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 35000m,
                            Quantity = 30,
                            Title = "Sách Lập trình Java",
                            UpdateAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Lê Thị C",
                            CategoryId = 3,
                            CreateAt = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hướng dẫn lập trình Python nâng cao.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 39000m,
                            Quantity = 25,
                            Title = "Sách Lập trình Python",
                            UpdateAt = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Phạm Văn D",
                            CategoryId = 4,
                            CreateAt = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lập trình JavaScript cơ bản.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 24000m,
                            Quantity = 40,
                            Title = "Sách Lập trình JavaScript",
                            UpdateAt = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Hoàng Thị E",
                            CategoryId = 5,
                            CreateAt = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ruby cơ bản và nâng cao.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 42000m,
                            Quantity = 35,
                            Title = "Sách Lập trình Ruby",
                            UpdateAt = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Đặng Văn F",
                            CategoryId = 6,
                            CreateAt = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "PHP từ cơ bản đến nâng cao.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 37000m,
                            Quantity = 20,
                            Title = "Sách Lập trình PHP",
                            UpdateAt = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Nguyễn Văn G",
                            CategoryId = 7,
                            CreateAt = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Học lập trình Swift.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 45000m,
                            Quantity = 25,
                            Title = "Sách Lập trình Swift",
                            UpdateAt = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Nguyễn Thị H",
                            CategoryId = 8,
                            CreateAt = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lập trình Kotlin từ A đến Z.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 33000m,
                            Quantity = 30,
                            Title = "Sách Lập trình Kotlin",
                            UpdateAt = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Lê Văn I",
                            CategoryId = 9,
                            CreateAt = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Objective-C cơ bản và nâng cao.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 39000m,
                            Quantity = 15,
                            Title = "Sách Lập trình Objective-C",
                            UpdateAt = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Trần Văn J",
                            CategoryId = 10,
                            CreateAt = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "R cho dữ liệu.",
                            ImageUrl = "https://images.pexels.com/photos/3643828/pexels-photo-3643828.jpeg?cs=srgb&dl=pexels-ena-marinkovic-1814213-3643828.jpg&fm=jpg",
                            Price = 29000m,
                            Quantity = 20,
                            Title = "Sách Lập trình R",
                            UpdateAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("backend.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDanhMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TaoLuc")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenDanhMuc");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CapNhatLuc")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("CategoryId");

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreateAt = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình C#",
                            UpdateAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 2,
                            CreateAt = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình Java",
                            UpdateAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 3,
                            CreateAt = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình Python",
                            UpdateAt = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 4,
                            CreateAt = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình JavaScript",
                            UpdateAt = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 5,
                            CreateAt = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình Ruby",
                            UpdateAt = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 6,
                            CreateAt = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình PHP",
                            UpdateAt = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 7,
                            CreateAt = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình Swift",
                            UpdateAt = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 8,
                            CreateAt = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình Kotlin",
                            UpdateAt = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 9,
                            CreateAt = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình Objective-C",
                            UpdateAt = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 10,
                            CreateAt = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lập trình R",
                            UpdateAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("backend.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBinhLuan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("MaSach");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TaoLuc")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CapNhatLuc")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenTaiKhoan");

                    b.HasKey("Id");

                    b.HasIndex("AccountUsername");

                    b.HasIndex("BookId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("backend.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDonHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TaoLuc")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("TongTien");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CapNhatLuc")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTaiKhoan");

                    b.HasKey("Id");

                    b.HasIndex("AccountUsername");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("backend.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietDonHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("MaSach");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TaoLuc")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("MaDonHang");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("DonGia");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CapNhatLuc")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("backend.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTrangThai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTrangThai");

                    b.HasKey("Id");

                    b.ToTable("TrangThaiDonHang");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Chuẩn bị hàng"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Đang giao hàng"
                        },
                        new
                        {
                            Id = 3,
                            StatusName = "Đã giao hàng"
                        });
                });

            modelBuilder.Entity("backend.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaQuyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenQuyen");

                    b.HasKey("Id");

                    b.ToTable("Quyen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("backend.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLichSuTrangThai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TaoLuc")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("MaDonHang");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int")
                        .HasColumnName("MaTrangThai");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CapNhatLuc")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("LichSuTrangThai");
                });

            modelBuilder.Entity("backend.Account", b =>
                {
                    b.HasOne("backend.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Book", b =>
                {
                    b.HasOne("backend.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("backend.Comment", b =>
                {
                    b.HasOne("backend.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountUsername");

                    b.HasOne("backend.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("backend.Order", b =>
                {
                    b.HasOne("backend.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountUsername");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("backend.OrderDetail", b =>
                {
                    b.HasOne("backend.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("backend.StatusHistory", b =>
                {
                    b.HasOne("backend.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("backend.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("backend.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
